AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Feature Usage Lambda Functions

Parameters:
  Env:
    Type: String
    Default: local
    AllowedValues:
      - local
      - staging
      - production
  TtlDays:
    Type: Number
    Default: 90
    Description: Number of days before DynamoDB items expire via TTL
  MaxDateRangeDays:
    Type: Number
    Default: 1825
    Description: Maximum allowed date range in days for metric queries
  LambdaTimeout:
    Type: Number
    Default: 30
    Description: Lambda function timeout in seconds
  LambdaMemorySize:
    Type: Number
    Default: 256
    Description: Lambda function memory size in MB
  ReservedConcurrency:
    Type: Number
    Default: 10
    Description: Reserved concurrent executions for the updates handler
  SqsBatchSize:
    Type: Number
    Default: 10
    Description: Number of SQS messages per Lambda invocation
  SqsVisibilityTimeout:
    Type: Number
    Default: 60
    Description: SQS visibility timeout in seconds
  MaxReceiveCount:
    Type: Number
    Default: 3
    Description: Max delivery attempts before routing to DLQ
  DlqRetentionPeriod:
    Type: Number
    Default: 1209600
    Description: DLQ message retention in seconds (default 14 days)
  ErrorAlarmThreshold:
    Type: Number
    Default: 5
    Description: Number of Lambda errors to trigger the alarm
  ErrorAlarmPeriod:
    Type: Number
    Default: 60
    Description: CloudWatch metric evaluation period in seconds for the error alarm
  ErrorAlarmEvaluationPeriods:
    Type: Number
    Default: 3
    Description: Number of consecutive periods before the error alarm fires
  QueryReservedConcurrency:
    Type: Number
    Default: 10
    Description: Reserved concurrent executions for the query handler
  LogLevel:
    Type: String
    Default: info
    AllowedValues:
      - debug
      - info
      - warn
      - error
    Description: Minimum log level for Lambda functions
  LogRetentionDays:
    Type: Number
    Default: 30
    Description: CloudWatch log group retention in days

Globals:
  Function:
    Runtime: nodejs22.x
    Timeout: !Ref LambdaTimeout
    MemorySize: !Ref LambdaMemorySize
    Tracing: Active
    Layers:
      - !Sub arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:53
    Environment:
      Variables:
        ENV: !Ref Env
        TTL_DAYS: !Ref TtlDays
        MAX_DATE_RANGE_DAYS: !Ref MaxDateRangeDays
        LOG_LEVEL: !Ref LogLevel

Resources:
  MetricQueryHandler:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/metric-query.handler.main
      CodeUri: .
      ReservedConcurrentExecutions: !Ref QueryReservedConcurrency
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:Query
              Resource: !GetAtt UsageTable.Arn
        - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/metric-query.handler.ts

  MetricUpdatesHandler:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/metric-updates.handler.main
      CodeUri: .
      ReservedConcurrentExecutions: !Ref ReservedConcurrency
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt UsageQueue.Arn
            BatchSize: !Ref SqsBatchSize
            FunctionResponseTypes:
              - ReportBatchItemFailures
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:UpdateItem
                - dynamodb:PutItem
              Resource: !GetAtt UsageTable.Arn
        - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/metric-updates.handler.ts

  QueryHandlerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${MetricQueryHandler}
      RetentionInDays: !Ref LogRetentionDays

  UpdatesHandlerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${MetricUpdatesHandler}
      RetentionInDays: !Ref LogRetentionDays

  UsageTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Sub feature-usage-${Env}
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  UsageQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub feature-usage-updates-${Env}
      SqsManagedSseEnabled: true
      VisibilityTimeout: !Ref SqsVisibilityTimeout
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt UsageDeadLetterQueue.Arn
        maxReceiveCount: !Ref MaxReceiveCount

  UsageDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub feature-usage-updates-dlq-${Env}
      SqsManagedSseEnabled: true
      MessageRetentionPeriod: !Ref DlqRetentionPeriod

  AlarmNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub feature-usage-alarms-${Env}

  DLQDepthAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Messages arriving in the dead letter queue
      Namespace: AWS/SQS
      MetricName: ApproximateNumberOfMessagesVisible
      Dimensions:
        - Name: QueueName
          Value: !GetAtt UsageDeadLetterQueue.QueueName
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 0
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlarmNotificationTopic
      OKActions:
        - !Ref AlarmNotificationTopic

  UpdatesHandlerErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Updates handler error rate exceeded threshold
      Namespace: AWS/Lambda
      MetricName: Errors
      Dimensions:
        - Name: FunctionName
          Value: !Ref MetricUpdatesHandler
      Statistic: Sum
      Period: !Ref ErrorAlarmPeriod
      EvaluationPeriods: !Ref ErrorAlarmEvaluationPeriods
      Threshold: !Ref ErrorAlarmThreshold
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlarmNotificationTopic
      OKActions:
        - !Ref AlarmNotificationTopic

  QueryHandlerErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Query handler error rate exceeded threshold
      Namespace: AWS/Lambda
      MetricName: Errors
      Dimensions:
        - Name: FunctionName
          Value: !Ref MetricQueryHandler
      Statistic: Sum
      Period: !Ref ErrorAlarmPeriod
      EvaluationPeriods: !Ref ErrorAlarmEvaluationPeriods
      Threshold: !Ref ErrorAlarmThreshold
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlarmNotificationTopic
      OKActions:
        - !Ref AlarmNotificationTopic

  QueryHandlerThrottleAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Query handler is being throttled due to reserved concurrency exhaustion
      Namespace: AWS/Lambda
      MetricName: Throttles
      Dimensions:
        - Name: FunctionName
          Value: !Ref MetricQueryHandler
      Statistic: Sum
      Period: !Ref ErrorAlarmPeriod
      EvaluationPeriods: !Ref ErrorAlarmEvaluationPeriods
      Threshold: 0
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlarmNotificationTopic
      OKActions:
        - !Ref AlarmNotificationTopic

Outputs:
  QueryHandlerArn:
    Value: !GetAtt MetricQueryHandler.Arn
  UpdatesHandlerArn:
    Value: !GetAtt MetricUpdatesHandler.Arn
  QueueUrl:
    Value: !Ref UsageQueue
  DeadLetterQueueUrl:
    Value: !Ref UsageDeadLetterQueue
  TableName:
    Value: !Ref UsageTable
